name: bioinf
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core bioinformatics tools that work across platforms
  - samtools
  - bcftools
  - bedtools
  - bwa
  - minimap2
  - seqtk
  - seqkit
  - csvkit
