name: CI/CD Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh
        run: sudo apt-get update && sudo apt-get install -y zsh
      - name: Copy config template
        run: cp config.ini.template ci-config.ini
      - name: Run non-interactive installation
        run: ./install.sh --non-interactive --config ci-config.ini
      - name: Verify installation
        run: |
          zsh -c "source $HOME/.zshrc && command -v bat && command -v micromamba"
      - name: Test micromamba environment
        run: |
          zsh -c "source $HOME/.zshrc && micromamba --version"
      - name: Verify modern tools
        run: |
          zsh -c "source $HOME/.zshrc && eza --version || exa --version"
          zsh -c "source $HOME/.zshrc && bat --version || batcat --version"
          zsh -c "source $HOME/.zshrc && rg --version"

  test-macos:
    runs-on: macos-latest
    needs: test-ubuntu
    steps:
      - uses: actions/checkout@v3
      - name: Copy config template
        run: cp config.ini.template ci-config.ini
      - name: Run non-interactive installation
        run: ./install.sh --non-interactive --config ci-config.ini
      - name: Verify installation
        run: |
          zsh -c "source $HOME/.zshrc && command -v bat && command -v micromamba"
      - name: Test micromamba environment
        run: |
          zsh -c "source $HOME/.zshrc && micromamba --version"
      - name: Verify modern tools
        run: |
          zsh -c "source $HOME/.zshrc && eza --version || exa --version"
          zsh -c "source $HOME/.zshrc && bat --version"
          zsh -c "source $HOME/.zshrc && rg --version"

  build-docker:
    runs-on: ubuntu-latest
    needs: [test-ubuntu, test-macos]
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t bioinf-cli-env .
      - name: Test Docker image
        run: |
          docker run --rm bioinf-cli-env zsh -c "micromamba --version"
          docker run --rm bioinf-cli-env zsh -c "bat --version || batcat --version"
