name: CI/CD Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set permissions
        run: chmod +x ./install.sh

      - name: Install zsh
        run: sudo apt-get update && sudo apt-get install -y zsh || { echo "Failed installing zsh"; exit 1; }

      - name: Copy config template
        run: cp config.ini.template ci-config.ini

      - name: Run non-interactive installation
        run: ./install.sh --non-interactive --config ci-config.ini || { echo "Install script failed"; exit 1; }

      - name: Verify installation
        run: |
          export PATH="$HOME/.local/bin:$HOME/micromamba/bin:$PATH"
          # Check for binaries directly installed in standard locations
          if command -v bat || command -v batcat || [ -f "$HOME/.local/bin/bat" ] || [ -f "$HOME/.local/bin/batcat" ]; then
            echo "Bat/batcat found"
          else
            echo "Bat not found in PATH or standard locations"
            echo "Current PATH: $PATH"
            ls -la $HOME/.local/bin || echo "Can't list .local/bin"
            apt-cache policy bat batcat || echo "Can't check package status"
            exit 1
          fi
          
          # Check for micromamba
          if command -v micromamba || [ -f "$HOME/micromamba/bin/micromamba" ]; then
            echo "Micromamba found"
          else
            echo "Micromamba binary not found within expected directories"
            echo "Current PATH: $PATH"
            ls -la $HOME/micromamba/bin || echo "Can't list micromamba bin dir"
            exit 1
          fi

  test-macos:
    runs-on: macos-latest
    needs: test-ubuntu
    steps:
      - uses: actions/checkout@v3

      - name: Set permissions
        run: chmod +x ./install.sh
      - name: Copy config template
        run: cp config.ini.template ci-config.ini
      - name: Run non-interactive installation
        run: ./install.sh --non-interactive --config ci-config.ini || { echo "MacOS install failed"; exit 1; }
      - name: Debug .zshrc
        run: |
          echo "Contents of ~/.zshrc:"
          cat "$HOME/.zshrc"
      - name: Verify installation
        run: |
          echo "Current PATH: $PATH"
          source "$HOME/.zshrc" || { echo "MacOS sourcing ~/.zshrc failed"; exit 1; }
          echo "Updated PATH: $PATH"
          command -v bat || { echo "MacOS Bat not found"; exit 1; }
          command -v micromamba || { echo "MacOS Micromamba not found"; exit 1; }

  build-docker:
    runs-on: ubuntu-latest
    needs: [test-ubuntu, test-macos]
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t bioinf-cli-env . || { echo "Docker build failed"; exit 1; }

      - name: Test Docker image
        run: |
          docker run --rm bioinf-cli-env zsh -c "command -v micromamba" || { echo "Micromamba missing in container"; exit 1; }
          docker run --rm bioinf-cli-env zsh -c "command -v bat || command -v batcat" || { echo "Bat missing in container"; exit 1; }
